@Istest
public class TestDataFactory_TestClass {
    @Istest
    public static void testdata(){
        TestDataFactory.doclist();
        TestDataFactory.accList();
        TestDataFactory.CaseMethod(true);
        TestDataFactory.conMethod(true);
        //TestDataFactory.createUser();
        //TestDataFactory.ConversationEntryInsertMethod();
        TestDataFactory.csList();
        TestDataFactory.emList();
        TestDataFactory.createAgentChoices();
        // TestDataFactory.VCList(true);
        TestDataFactory.LCList(true);
        TestDataFactory.MsgMethod();
        TestDataFactory.MessagingMethod();
        TestDataFactory.createAgentWorkflowParent();
        TestDataFactory.createAgentWorkflowChild();
        //TestDataFactory.createAgentWorkflowChoices();
    }
    
}